### PR TITLE
Fixes #1114 possible xss issue

### LINKED ISSUE #1114: Possible XSS Vulnerability
## Type of issue
Possible XSS security vulnerability.

## Description
After generating Prebid.js (using gulp), line 376 (in Prebix v0.21.0) 

url, width, and height parameters should be added using DOM manipulator functions, otherwise it might be XSS vulnerable

```
doc.write('<IFRAME SRC="' + url + '" FRAMEBORDER="0" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" TOPMARGIN="0" LEFTMARGIN="0" ALLOWTRANSPARENCY="true" WIDTH="' + width + '" HEIGHT="' + height + '"></IFRAME>');
```

## Steps to reproduce
Generate prebid.js using:
`gulp serve --adapters /path/to/my/vendors.json`

This is my vendors.json
```
[
    "appnexus",
    "indexExchange",
    "pubmatic",
    "rubicon",
    "sovrn",
    "triplelift",
    "centro",
    "sharethrough",
    {
      "rubicon": {
        "alias": "rubiconLite",
        "supportedMediaTypes": ["video"]
      }
    }
]
```

### Expected results
Any generated HTML should use DOM manipulator functions instead of arbitrarily building a string of HTML, e.g. something like..

```
var iframe = document.createElement('iframe');
iframe.src = encodeURI(url);
iframe.width = width;
iframe.height = height;
...
```

### Actual results
```
doc.write('<IFRAME SRC="' + url + '" FRAMEBORDER="0" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" TOPMARGIN="0" LEFTMARGIN="0" ALLOWTRANSPARENCY="true" WIDTH="' + width + '" HEIGHT="' + height + '"></IFRAME>');
```

## Platform details
Prebid v0.21.0
Generating with OS X 10.12.4
NPM v3.10.8

## Other information
None

### PR DESCRIPTION
**Pull request by mkendall07**
## Type of change

- [x] Refactoring (no functional changes, no api changes)
## Description of change
Addresses #1114 

## Other information
This is super critical code, so review should be rigorous.

### CODE REVIEW

File: test/spec/unit/pbjs_api_spec.js [hunk 1]
```diff
@@ -573,8 +580,9 @@ describe('Unit: Prebid Module', function () {
     it('should place the url inside an iframe on the doc', function () {
       adResponse.adUrl = 'http://server.example.com/ad/ad.js';
       $$PREBID_GLOBAL$$.renderAd(doc, bidId);
-      var iframe = '<IFRAME SRC="' + adResponse.adUrl + '" FRAMEBORDER="0" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" TOPMARGIN="0" LEFTMARGIN="0" ALLOWTRANSPARENCY="true" WIDTH="' + adResponse.width + '" HEIGHT="' + adResponse.height + '"></IFRAME>';
-      assert.ok(doc.write.calledWith(iframe), 'url was written to iframe in doc');
+      //var iframe = '<IFRAME SRC="' + adResponse.adUrl + '" FRAMEBORDER="0" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" TOPMARGIN="0" LEFTMARGIN="0" ALLOWTRANSPARENCY="true" WIDTH="' + adResponse.width + '" HEIGHT="' + adResponse.height + '"></IFRAME>';
```
Comment (dbemiller) [inline test/spec/unit/pbjs_api_spec.js]: Better to get rid of code, over leaving it commented.
