### PR TITLE
Emit array of objects from BID_TIMEOUT event

### LINKED ISSUE #844: Add requestId and unit id to the timeout event.
## Description
Add requestId and unit id to the timeout event?

## Steps to reproduce
The timeout event only sends back for bidder(s) without including any additional information.

### Expected results
Timeout events should pass along information like the other events.

### Actual results
A list of bidders which have timed out.

### PR DESCRIPTION
**Pull request by matthewlane**
## Type of change
- Other

## Description of change
Changes the data payload emitted from the `BID_TIMEOUT` event from an array of bidder codes strings, to an array of objects containing the bid id, bidder code, ad unit code, and auction id (this is equivalent to `requestId` in pre-1.0) for each timed out bid.

Before
```JavaScript
["bidderOne", "bidderTwo"]
```

After
```JavaScript
[
  {
    "bidId": "2baa51527bd015",
    "bidder": "bidderOne",
    "adUnitCode": "/19968336/header-bid-tag-0",
    "auctionId": "66529d4c-8998-47c2-ab3e-5b953490b98f"
  },
  {
    "bidId": "6fe3b4c2c23092",
    "bidder": "bidderTwo",
    "adUnitCode": "/19968336/header-bid-tag-0",
    "auctionId": "66529d4c-8998-47c2-ab3e-5b953490b98f"
  }
]
```

## Other information
Closes #844

### CODE REVIEW

**Comment by mkendall07** [comment]
CC analytics contributors:
@Yann-Pravo 
@adxcgcom
@GLStephen 
@sergey-roxot 
@chriscpan 
@anand-venkatraman 
@chensMMG 

This will require an update in the 1.0 branch for analytics if you are listening to the `BID_TIMEOUT` event.

File: src/auction.js [hunk 1]
```diff
@@ -132,27 +132,47 @@ export function newAuction({adUnits, adUnitCodes, callback, cbTimeout, labels})
...
+      .filter(bidder => !bidReceivedCodes.includes(bidder));
+
+    const timedOutBids = _bidderRequests
+      .map(bid => (bid.bids || []).filter(bid => timedOutBidderCodes.includes(bid.bidder)))
+      .reduce(flatten, [])
+      .map(bid => ({
+        bidId: bid.bidId,
+        bidder: bid.bidder,
+        adUnitCode: bid.adUnitCode,
+        requestId: bid.requestId,
```
Comment (matthewlane) [inline src/auction.js]: In testing this is coming through as `undefined`, tracking that down, don't merge in meantime

**Comment by GLStephen** [comment]
@mkendall07 thanks for the heads up, this change is good, the extra detail is helpful and was on our radar
