### PR TITLE
Respect prebid global

### LINKED ISSUE #1340: $PREBID_GLOBAL$$ not respected in some Adapters
## Type of issue
Bug

## Description
The following Adapters are not respecting the global naming convention, but they hardcode the `pbjs` variable instead.

- [eplanningBidAdapter.js](https://github.com/prebid/Prebid.js/blob/master/modules/eplanningBidAdapter.js)
- [jcmBidAdapter.js](https://github.com/prebid/Prebid.js/blame/master/modules/jcmBidAdapter.js)  

## Steps to reproduce
- Open the files linked before [eplanningBidAdapter.js:241](https://github.com/prebid/Prebid.js/blob/master/modules/eplanningBidAdapter.js#L241) & [jcmBidAdapter.js:8](https://github.com/prebid/Prebid.js/blob/master/modules/jcmBidAdapter.js#L8)

### Expected results

I expect to don't have any `pbjs` hardcoded value into the final bundle

### Actual results
I can see the variable, this will make the adapter fails if the global name is different from the defualt, plus it will eventually fail on avoid conflicts for multiple loads of prebid.js (3rd party)

## Platform details
All

## Other information
None

### PR DESCRIPTION
**Pull request by dbemiller**
## Type of change
Bugfix

## Description of change
I had planned on fixing the JCM adapter for #1340, thinking it'd be easy. I was wrong; their server's response assumes `pbjs`, so I can't change it in this project.

But... something slightly useful did come from it. When testing their adapter, I did `gulp serve` after changing the `globalVarName` in my `package.json`.

That surfaced many unit test failures, because the test files themselves weren't respecting `$$PREBID_GLOBAL$$`.

So... we'll have to wait for @JCarterGw to fix #1340, but we still may as well fix our test code.

### CODE REVIEW

**Comment by dantarion** [comment]
This will also fix #1437 for me.

File: test/spec/modules/jcmBidAdapter_spec.js [hunk 1]
```diff
@@ -198,7 +198,7 @@ describe('jcm adapter tests', function () {
     var response = '{"bids":[{"width":300,"cpm":3,"ad":"%3Cimg+src%3D%22http%3A%2F%2Fmedia.adfrontiers.com%2Fimgs%2Fpartnership_300x250.png%22%3E","callbackId":"3c9408cdbf2f68","height":250},{"width":728,"cpm":0,"ad":"%3Cimg+src%3D%22http%3A%2F%2Fmedia.adfrontiers.com%2Fimgs%2Fpartnership_728x90.png%22%3E","callbackId":"3c9408cdbf2f69","height":90}]}';
 
     it('callback function should exist', function () {
-      expect($$PREBID_GLOBAL$$.processJCMResponse).to.exist.and.to.be.a('function');
```
Comment (mkendall07) [inline test/spec/modules/jcmBidAdapter_spec.js]: Why the reverse switch here? @dbemiller

Comment (dbemiller) [inline test/spec/modules/jcmBidAdapter_spec.js]: Due to [this issue](https://github.com/prebid/Prebid.js/issues/1340#issuecomment-319710240) from the discussion in #1340.

Since their server hardcodes `pbjs` into its JSONP response, we can't change [this line](https://github.com/prebid/Prebid.js/blob/master/modules/jcmBidAdapter.js#L9), without breaking their adapter.

I couldn't change the source, so... I changed the test instead.

**Comment by mkendall07** [comment]
Respect 💯
