### PR TITLE
Fix #3265 - pbs cookie sync race condition

### LINKED ISSUE #3265: Prebid Server cookie sync race condition
## Type of issue
Bug

## Description

There's a race condition in the `prebidServerBidAdapter` cookie sync code: https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L119

Prebid Server's /setuid endpoint behaves like so:

1. Unpack the Cookie sent in the request, to get existing user IDs.
2. Update the data inside the Cookie with the new Bidder/UID
3. Respond with a Set-Cookie header with the updated data.

Suppose two syncs get executed, and the second one gets sent before the first one returns. The same Cookie data will be sent to both. Both `/setuid` calls will respond with `Set-Cookie` headers, but neither one will contain the other one's data. After both execute, the final cookie will only have the updated ID from the _last_ `/setuid` response to return.

## Steps to reproduce

Since this is a race condition, it's inherently impossible to reproduce reliably. To increase the chances of reproducing it, run an auction with all the Prebid Server bidders. Use a `baset64` decoder to decode the PBS cookie, and see whether all the bidders have syncs there.

In practice, there's probably not much value in reproducing it. To fix it, just do your best to avoid running two Prebid Server cookie syncs at the same time.

### PR DESCRIPTION
**Pull request by jsnellbaker**
## Type of change

- [x] Bugfix

## Description of change
Fixes #3265

### CODE REVIEW

File: modules/prebidServerBidAdapter/index.js [hunk 1]
```diff
@@ -128,24 +128,39 @@ function queueSync(bidderCodes, gdprConsent) {
...
+
 /**
  * Run a cookie sync for the given type, url, and bidder
  *
  * @param {string} type the type of sync, "image", "redirect", "iframe"
  * @param {string} url the url to sync
  * @param {string} bidder name of bidder doing sync for
  */
-function doBidderSync(type, url, bidder) {
+function doBidderSync(type, url, bidder, done) {
```
Comment (mkendall07) [inline modules/prebidServerBidAdapter/index.js]: can you update the JSdoc params for `done` ?

File: src/utils.js [hunk 2]
```diff
@@ -616,11 +620,15 @@ exports.insertHtmlIntoIframe = function(htmlCode) {
  * @param  {string} url URL to be requested
  * @param  {string} encodeUri boolean if URL should be encoded before inserted. Defaults to true
  */
-exports.insertUserSyncIframe = function(url) {
+exports.insertUserSyncIframe = function(url, done) {
```
Comment (mkendall07) [inline src/utils.js]: JS doc here too

**Comment by jsnellbaker** [comment]
@mkendall07 Thanks for the feedback; I added the missing jsdoc comments.
