### PR TITLE
UserID module: autoRefresh and retainConfig flags

### LINKED ISSUE #12104: user ids not present in bid requests
## Type of issue
bug

## Description
User ids are not present in bid requests on 247sports.com most of the time. I am seeing the user ids present in the bid requests _very_ infrequently, like every few days for one or two page reloads. This is working as expected 100% of the time on some of our other properties (comicbook.com, insideedition.com, cbssports.com for example) with the same implementation. The user ids are present in the userSync config (`pbjs.getConfig().userSync.userIds`), but not in the Prebid userIds object (`pbjs.getUserIds()`).

## Steps to reproduce
1. go to https://247sports.com/?pbjs_debug=true
2. filter the console by "requested" and drill into an individual bid and notice that the `userId` object is not present
3. execute `pbjs.getConfig().userSync.userIds` in the console to see that the userSync config is set properly
4. execute `pbjs.getUserIds()` to see an empty prebid userIds object

### Expected results
If the `userSync.userIds` config is set, there should be a `userId` object in the bid requests and running `pbjs.getUserIds()` should produce a non-empty object.

### Actual results
There is no `userId` object in the bid requests.

### PR DESCRIPTION
**Pull request by mkomorski**
## Type of change

- [x] Feature

## Other information

Closes #12104

### CODE REVIEW

File: modules/userId/index.js [hunk 1]
```diff
@@ -1248,12 +1268,17 @@ export function init(config, {mkDelay = delay} = {}) {
     if (userSync) {
       ppidSource = userSync.ppid;
       if (userSync.userIds) {
+        const {autoRefresh = false, retainConfig = true} = userSync;
```
Comment (dgirardi) [inline modules/userId/index.js:1271]: I know the defaults are my idea, but could you check if they match what's currently in master? retainConfig = true means that it should be the current behavior (or a breaking change), but that doesn't seem to be the case judging from your changes here.

Comment (dgirardi) [reply modules/userId/index.js:1271]: actually , I missed that this is for 10, so the breaking change is OK.

**Review by dgirardi — APPROVED** [review]
