### PR TITLE
Yieldbot adunit bidder params slot name usage fix

### LINKED ISSUE #1392: Yieldbot, adapter param configs using the same slot name
## Type of issue

- **Bug**

## Description

For adUnits where the same Yieldbot bidder params slot name is used ( `slot: <slotName>` ), the Yieldbot adapter would add a bid, `addBidResponse(adUnitCode, bid)`.

Yieldbot bids for a single slot and dimension only. Therefore, each Yieldbot bid response slot shall be considered to be fore a single adUnit declaration.

e.g. this kind of config
```
var adUnits = [
  {
      code: 'div-gpt-ad-1438287399331-1',
      sizes: [[300, 250], [300, 600]],
      bids: [
          {
              bidder: 'yieldbot',
              params: {
                  psn: '1234',
                  slot: 'test_slot'
              }
          }
      ]
  },
  {
      code: 'div-gpt-ad-1438287399331-2',
      sizes: [[300, 250]],
      bids: [
          {
              bidder: 'yieldbot',
              params: {
                  psn: '1234',
                  slot: 'test_slot'
              }
          }
      ]
  }
]
```

## Steps to reproduce

1. Open https://fiddle.jshell.net/ybelljoh/4zbdtrox/show/#enable
 - Edit the [Fiddle](https://fiddle.jshell.net/ybelljoh/4zbdtrox/) if you wish
2. Hit the link "**Enable - Yieldbot Test Bids**"
 - Close the newly focused tab that enables Yieldbot testing mode
3. Open devtools; or your preferred browser console so you can see network request/response
4. Refresh / re-run the Fiddle
5. Observe

5.1 Yieldbot response; filter network requests by "`yldbt`" and look at the request for `init` **Preview** tab
 
  - You'll see ***two*** bids

5.2 DFP response; filter network requests by "`gamp`" and look at the request for `ads` **Preview** tab
 
  - You'll see ***three*** creatives returned

***Note:*** You will not see the DFP creative rendered. This is **NOT** a bug, just haven't figured out how to get DFP 1x1 creatives with "Override" set to render in the JSFiddle cross-origin frames.

### Expected results

**Yieldbot Response**
```
  "slots": [{
    "slot": "leaderboard",
    "cpm": "800",
    "size": "728x90"
  }, {
    "slot": "test_slot",
    "cpm": "200",
    "size": "300x250"
  }]
```

**DFP Response**
```
googletag.impl.pubads.callbackProxy1([{
  "/2476204/leaderboard": {
...
    "_html_": "\x3c Creative code here \x3e",
    "_snippet_": true,
    "_height_": 1,
    "_width_": 1,
    "_empty_": false,
...
  }
}, {
  "/2476204/multi-size": {
...
    "_html_": "\x3c Creative code here \x3e",
    "_snippet_": true,
    "_height_": 1,
    "_width_": 1,
    "_empty_": false,
...
  }
}, {
  "/2476204/multi-size": {
...
    "_html_": "",
    "_snippet_": false,
    "_height_": 250,
    "_width_": 300,
    "_empty_": true,
  }
}]);
```

### Actual results

Note the additional `/2476204/multi-size` response element `"_html_": "\x3c Creative code here \x3e"`

**DFP Response**
```
googletag.impl.pubads.callbackProxy1([{
  "/2476204/leaderboard": {
...
    "_html_": "\x3c Creative code here \x3e",
    "_snippet_": true,
    "_height_": 1,
    "_width_": 1,
    "_empty_": false,
...
  }
}, {
  "/2476204/multi-size": {
...
    "_html_": "\x3c Creative code here \x3e",
    "_snippet_": true,
    "_height_": 1,
    "_width_": 1,
    "_empty_": false,
...
  }
}, {
  "/2476204/multi-size": {
...
    "_html_": "\x3c Creative code here \x3e",
    "_snippet_": true,
    "_height_": 1,
    "_width_": 1,
    "_empty_": false,
...
}
}]);
```

## Platform details

- Prebid.js: <= `0.26.0`
- Node: `7.0.0`

## Other information

Creating this bug for the record related to a pull request to come for resolution of this bug.

- You can assign to `@elljoh`

### PR DESCRIPTION
**Pull request by elljoh**
## Type of change

- [x] Bugfix
- [x] Example

## Description of change

Resolves #1392 

AdUnit configuration that uses the same slot name for the Yieldbot bidder params, i.e. multiple occurrences such as the below, results in erroneous  `bidmanager.addBidResponse(...)` calls.

```
          {
              bidder: 'yieldbot',
              params: {
                  psn: '1234',
                  slot: 'test_slot'
              }
          }
``` 

See Issue #1392 for more details.

## Other information

Resolves #1392

### CODE REVIEW

**Comment by jaiminpanchal27** [comment]
@elljoh You have conflicts. Please rebase with master

**Comment by elljoh** [comment]
@jaiminpanchal27 heya, rebased to `master`.

**Comment by elljoh** [comment]
@jaiminpanchal27 lmk if there is anything else needed here. thanks!

**Comment by jaiminpanchal27** [comment]
@elljoh Will check it today. Thanks

File: test/spec/modules/yieldbotBidAdapter_spec.js [hunk 1]
```diff
@@ -84,28 +97,103 @@ function setupTest() {
...
+  const ybAdapter = new YieldbotAdapter();
+  let request = testRequest || cloneJson(bidderRequest);
+  ybAdapter.callBids(request);
   mockYieldbotBidRequest();
+  return { adapter: ybAdapter, localRequest: request };
 }
 
+function removeBids(bidder) {
+  if (window && window.pbjs) {
+    window.pbjs._bidsRequested = window.pbjs._bidsRequested.filter(o => {
```
Comment (jaiminpanchal27) [inline test/spec/modules/yieldbotBidAdapter_spec.js]: you should not touch pbjs private variables. This can break other tests.

File: test/spec/modules/yieldbotBidAdapter_spec.js [hunk 2]
```diff
@@ -84,28 +97,103 @@ function setupTest() {
...
+      const sizes = adapter.getUniqueSlotSizes(true);
+      expect(sizes).to.deep.equal([]);
     });
 
+    it('should return [] for undefined sizes', function() {
+      const sizes = adapter.getUniqueSlotSizes(undefined);
+      expect(sizes).to.deep.equal([]);
+    });
+
+    it('should return [] for function sizes', function() {
```
Comment (jaiminpanchal27) [inline test/spec/modules/yieldbotBidAdapter_spec.js]: duplicate test..

File: test/spec/modules/yieldbotBidAdapter_spec.js [hunk 3]
```diff
@@ -161,112 +254,225 @@ describe('Yieldbot adapter tests', function() {
...
-        return o.bidderCode !== 'yieldbot';
-      });
+      expect(window.yieldbot._initialized).to.equal(true);
 
-      const adapter = new YieldbotAdapter();
-      adapter.callBids(bidderRequest);
-      mockYieldbotBidRequest();
+      removeBids('yieldbot');
 
       let bidResponses = window.$$PREBID_GLOBAL$$._bidsReceived.filter(o => {
```
Comment (jaiminpanchal27) [inline test/spec/modules/yieldbotBidAdapter_spec.js]: you should not access pbjs private vars. you can test this by stubbing `bidmanager.addBidResponse`

**Comment by jaiminpanchal27** [comment]
@elljoh Any update ?

**Comment by elljoh** [comment]
@jaiminpanchal27 apologies, I'm out of the office until Monday 20170814. Will address your comments then.

Thank you.

**Comment by elljoh** [comment]
@jaiminpanchal27 hi. anything remain for this pull request to merge?

**Comment by jaiminpanchal27** [comment]
@elljoh We require 2 LGTM's for PR to merge. I have approved this so someone should take it. Let me assign someone so that we get this in. Thanks
