### PR TITLE
Yieldbot refresh - nextPageview with specific refresh slots

### LINKED ISSUE #1255: Yieldbot adapter uses previously defined slots for all refresh requestBids calls
## Type of issue
- ***Bug***

## Description
An initial page view results in a request for particular slot bids (`S`) from Yieldbot. Subsequent calls to `pbjs.requestBids()` for a subset or different set of slot bids (`S'`) will result in a request for the same slots, `S`, despite the call having been given the `S'` argument.

The requested adUnits shall be marshaled into Yieldbot slot bids here:
 - https://github.com/prebid/Prebid.js/blob/master/src/adapters/yieldbot.js#L101
 - omission to do so is a **bug**, since the `yieldbot.nextPageview()` implementation without an argument for slots, will result in *all* previously defined slots being requested for bids.

## Steps to reproduce
1.  Configure the Yieldbot to request two bids e.g.
```
     var adUnits = [{
       code: 'div-gpt-ad-1460505748561-0',
       sizes: [[300, 250], [300,600]],
       bids: [{
         bidder: 'yieldbot',
         params: {
           psn: '1234',
           slot: 'medrec'
         }
       }]
     },{
       code: 'div-gpt-ad-1460505661639-0',
       sizes: [[728, 90], [970, 90]],
       bids: [{
         bidder: 'yieldbot',
         params: {
           psn: '1234',
           slot: 'leaderboard'
         }
       }]
     }];
```
***ref:*** https://github.com/prebid/Prebid.js/blob/master/test/spec/e2e/gpt-examples/e2e_default.html#L11

2. Request bids e.g. as in the following test spec file:
***ref:*** https://github.com/prebid/Prebid.js/blob/master/test/spec/e2e/gpt-examples/e2e_default.html#L51

3. Request bids again, but for a single  `adUnitCodes` entry e.g.
```
        pbjs.requestBids({
            adUnitCodes: [ 'medrec' ],
            bidsBackHandler: sendAdserverRequest
        });
```

### Expected results
A Yieldbot `init/` request with parameters:
```
sn:medrec
ssz:300x250.300x600
```
### Actual results
```
sn:medrec|leaderboard
ssz:300x250.300x600|728x90.970x90
```

## Platform details
`v0.23.1`

### PR DESCRIPTION
**Pull request by elljoh**
## Type of change

- [x] Bugfix

## Description of change
Fixes #1255

`callBids(params)` after the first i.e. "refresh" bid requests will only include bids for `params.bids`.

## Other information

- Resolves #1255

### CODE REVIEW

File: src/adapters/yieldbot.js [hunk 1]
```diff
@@ -83,24 +83,35 @@ var YieldbotAdapter = function YieldbotAdapter() {
...
-          yieldbot.pub(psn);
-          yieldbot.defineSlot(slot, { sizes: bid.sizes || [] });
+          slots[slotName] = bid.sizes || [];
           ybotlib.definedSlots.push(bid.bidId);
         });
-        yieldbot.enableAsync();
+
         if (yieldbot._initialized !== true) {
+          yieldbot.pub(psn);
+          for (var slotName in slots) {
```
Comment (elljoh) [inline src/adapters/yieldbot.js]: @grevory added the check for own property and a test for the check.

The object being checked is created `var slots = {};` so, I expect pretty unlikely to be exposed to any injected properties causing an issue with iteration of the enumerable properties... However, it's _been known_ that overriding Object in the wild is not implausible.

Please comment here if you were thinking of any specific issues you had in mind.

Understood that it's generally accepted good form to be defensive on inherited properties.

If you're ok with this, I can squash the fork and merge the fork with upstream master. lmk.

Thanks!

**Comment by elljoh** [comment]
ok. rebasing to master and running tests for the #1177 move to modules, before pushing again.

**Comment by elljoh** [comment]
@grevory lmk if there is anything else I can do.

/elljoh

**Comment by elljoh** [comment]
@mkendall07 any chance you or @grevory can look at this?

Cheers, /elljoh

**Comment by mkendall07** [comment]
LGTM.
