### PR TITLE
fixes #3128 YieldlabBidAdapter is not using bidRequest.params.adSize

### LINKED ISSUE #3128: YieldlabBidAdapter is not using bidRequest.params.adSize as customsize in bidResponse
## Type of issue
Bug

## Description
The customsize is not used within the bidResponse. Instead it uses the primary size of the array bidRequest.sizes.

## Steps to reproduce
see screenshot below

### Expected results
The bidResponse should use the bidRequest.params.adSize as width and height for the response.

### Actual results
The bidResponse contains the wrong size and doesn't match to the creativeId for Yieldlab deal. The deal doesn't appear.

## Platform details
prebid 1.24.1

## Other information
image

Introduced in #3035

### PR DESCRIPTION
**Pull request by derdeka**
## Type of change
- [x] Bugfix

## Description of change
when bidRequest.params.adSize is available, it has to be used in bidResponse or it will impact ad delivery

## Other information
- fixes issue which was introduced in PR #3035 
- affected versions prebid 1.24.0, 1.24.1, 1.25.0

### CODE REVIEW

File: modules/yieldlabBidAdapter.js [hunk 1]
```diff
@@ -80,8 +80,8 @@ export const spec = {
         const bidResponse = {
           requestId: bidRequest.bidId,
           cpm: matchedBid.price / 100,
-          width: primarysize[0],
-          height: primarysize[1],
+          width: customsize[0],
+          height: customsize[1],
           creativeId: '' + matchedBid.id,
```
Comment (harpere) [inline modules/yieldlabBidAdapter.js]: Can you add a test for this change, or for the behavior in general?

Comment (derdeka) [reply modules/yieldlabBidAdapter.js]: The issue happens, if there is more than one size available. I've added a testcase for this.
